version: "3.9"
services:
  create-keys:
    container_name: create-keys
    image: iotaledger/hornet:2.0.1
    networks:
      peering_net:
        ipv4_address: 172.18.211.11
    volumes:
      - ./protocol_parameters.json:/app/protocol_parameters.json:ro
      - ./genesis:/app/genesis
    command:
      - "tool"
      - "ed25519-key"
      - "--hrp=edcas"
    profiles:
      - genesis
  create-snapshots:
    container_name: create-snapshots
    image: iotaledger/hornet:2.0.1
    networks:
      peering_net:
        ipv4_address: 172.18.211.11
    volumes:
      - ./protocol_parameters.json:/app/protocol_parameters.json:ro
      - ./snapshots:/app/snapshots
    command:
      - "tool"
      - "snap-gen"
      - "--protocolParametersPath=/app/protocol_parameters.json"
      - "--mintAddress=edcas1qrp5nflv9yxm6hdgjh8sht0mxjhkngsuf0uu66h8u2yx8lnhlnzu7dxxprd"
      - "--outputPath=/app/snapshots/hornet-1/full_snapshot.bin"
    profiles:
      - snapshots
  bootstrap-network:
    container_name: bootstrap-network
    image: iotaledger/hornet:2.0.1
    networks:
      peering_net:
        ipv4_address: 172.18.211.11
    env_file:
      - ".coordinator_env"
    volumes:
      - ./config_hornet.json:/app/config_hornet.json:ro
      - ./snapshots/hornet-1:/app/snapshots
      - ./privatedb/hornet-1:/app/privatedb
      - ./privatedb/state:/app/state
    command:
      - "tool"
      - "bootstrap-private-tangle"
      - "--configFile=/app/config_hornet.json"
      - "--snapshotPath=/app/snapshots/full_snapshot.bin"
      - "--databasePath=/app/privatedb"
      - "--cooStatePath=/app/state/coordinator.state"
    profiles:
      - bootstrap
  generate_public_key:
    container_name: generate_public_key
    image: frankthefish/inx-eddn:latest
    environment:
      - "NODE_URL=https://api.edcas.de:443"
      - "ZEROMQ_URL=tcp://eddn.edcd.io:9500"
      - "WALLET_PASSWORD=testwallet"
      - "WALLET_PATH=wallet/wallet.stronghold"
      - "NUM_OF_WORKERS=4"
      - "KEY_SAVE_LOCATION=public_key/public_key"
    command:
      - "./inx-eddn"
      - "--saveKey"
    volumes:
      - ./inx-eddn/wallet:/app/wallet
      - ./inx-eddn/public_key:/app/public_key
  #
  # Nodes
  #
  hornet-1:
    container_name: hornet-1
    image: iotaledger/hornet:2.0.1
    networks:
      peering_net:
        ipv4_address: 172.18.211.11
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    stop_grace_period: 5m
    ports:
      - "15611:15600/tcp"
      - "14265:14265/tcp"
      - "9311:9311/tcp"
      - "9011:9029/tcp"
      - "6011:6060/tcp"
    cap_drop:
      - ALL
    volumes:
      - ./config_hornet.json:/app/config_hornet.json:ro
      - ./privatedb/hornet-1:/app/privatedb
      - ./snapshots/hornet-1:/app/snapshots
    command:
      - "-c"
      - "config_hornet.json"
      - "--node.alias=hornet-1"
      - "--inx.enabled=true"
      - "--inx.bindAddress=172.18.211.11:9029"
      - "--p2p.identityPrivateKey=1f46fad4f538a031d4f87f490f6bca4319dfd0307636a5759a22b5e8874bd608f9156ba976a12918c16a481c38c88a7b5351b769adc30390e93b6c0a63b09b79"
      - "--p2p.peers=/ip4/172.18.211.12/tcp/15600/p2p/12D3KooWCKwcTWevoRKa2kEBputeGASvEBuDfRDSbe8t1DWugUmL,/ip4/172.18.211.13/tcp/15600/p2p/12D3KooWGdr8M5KX8KuKaXSiKfHJstdVnRkadYmupF7tFk2HrRoA,/ip4/172.18.211.14/tcp/15600/p2p/12D3KooWC7uE9w3RN4Vh1FJAZa8SbE8yMWR6wCVBajcWpyWguV73"
      - "--p2p.peerAliases=hornet-2,hornet-3,hornet-4"
      - "--debug.enabled=true"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=172.18.211.11:9311"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.211.11:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes
  hornet-2:
    container_name: hornet-2
    image: iotaledger/hornet:2.0.1
    networks:
      peering_net:
        ipv4_address: 172.18.211.12
    depends_on:
      hornet-1:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    stop_grace_period: 5m
    ports:
      - "14266:14265/tcp"
      - "15612:15600/tcp"
      - "9312:9311/tcp"
      - "9012:9029/tcp"
      - "6012:6060/tcp"
    cap_drop:
      - ALL
    volumes:
      - ./config_hornet.json:/app/config_hornet.json:ro
      - ./privatedb/hornet-2:/app/privatedb
      - ./snapshots/hornet-2:/app/snapshots
    command:
      - "-c"
      - "config_hornet.json"
      - "--node.alias=hornet-2"
      - "--inx.enabled=true"
      - "--inx.bindAddress=172.18.211.12:9029"
      - "--p2p.identityPrivateKey=a06b288ce7fc3b6f1e716f6f7d72050b53417aae4b305a68883550a3bb28597f254b082515a79391a7f13009b4133851a0c4d48e0e948809c3b46ff3e2500b4f"
      - "--p2p.peers=/ip4/172.18.211.11/tcp/15600/p2p/12D3KooWSagdVaCrS14GeJhM8CbQr41AW2PiYMgptTyAybCbQuEY,/ip4/172.18.211.13/tcp/15600/p2p/12D3KooWGdr8M5KX8KuKaXSiKfHJstdVnRkadYmupF7tFk2HrRoA,/ip4/172.18.211.14/tcp/15600/p2p/12D3KooWC7uE9w3RN4Vh1FJAZa8SbE8yMWR6wCVBajcWpyWguV73"
      - "--p2p.peerAliases=hornet-1,hornet-3,hornet-4"
      - "--debug.enabled=true"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=172.18.211.12:9311"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.211.12:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes
  hornet-3:
    container_name: hornet-3
    image: iotaledger/hornet:2.0.1
    networks:
      peering_net:
        ipv4_address: 172.18.211.13
    depends_on:
      hornet-1:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    stop_grace_period: 5m
    ports:
      - "14267:14265/tcp"
      - "15613:15600/tcp"
      - "9313:9311/tcp"
      - "9013:9029/tcp"
      - "6013:6060/tcp"
    cap_drop:
      - ALL
    volumes:
      - ./config_hornet.json:/app/config_hornet.json:ro
      - ./privatedb/hornet-3:/app/privatedb
      - ./snapshots/hornet-3:/app/snapshots
    command:
      - "-c"
      - "config_hornet.json"
      - "--node.alias=hornet-3"
      - "--inx.enabled=true"
      - "--inx.bindAddress=172.18.211.13:9029"
      - "--p2p.identityPrivateKey=5126767a84e1ced849dbbf2be809fd40f90bcfb81bd0d3309e2e25e34f803bf265500854f1f0e8fd3c389cf7b6b59cfd422b9319f257e2a8d3a772973560acdd"
      - "--p2p.peers=/ip4/172.18.211.11/tcp/15600/p2p/12D3KooWSagdVaCrS14GeJhM8CbQr41AW2PiYMgptTyAybCbQuEY,/ip4/172.18.211.12/tcp/15600/p2p/12D3KooWCKwcTWevoRKa2kEBputeGASvEBuDfRDSbe8t1DWugUmL,/ip4/172.18.211.14/tcp/15600/p2p/12D3KooWC7uE9w3RN4Vh1FJAZa8SbE8yMWR6wCVBajcWpyWguV73"
      - "--p2p.peerAliases=hornet-1,hornet-2,hornet-4"
      - "--debug.enabled=true"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=172.18.211.13:9311"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.211.13:6060"
    profiles:
      - 3-nodes
      - 4-nodes
  hornet-4:
    container_name: hornet-4
    image: iotaledger/hornet:2.0.1
    networks:
      peering_net:
        ipv4_address: 172.18.211.14
    depends_on:
      hornet-1:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    stop_grace_period: 5m
    ports:
      - "14268:14265/tcp"
      - "15614:15600/tcp"
      - "9314:9311/tcp"
      - "9014:9029/tcp"
      - "6014:6060/tcp"
    cap_drop:
      - ALL
    volumes:
      - ./config_hornet.json:/app/config_hornet.json:ro
      - ./privatedb/hornet-4:/app/privatedb
      - ./snapshots/hornet-4:/app/snapshots
    command:
      - "-c"
      - "config_hornet.json"
      - "--node.alias=hornet-4"
      - "--inx.enabled=true"
      - "--inx.bindAddress=172.18.211.14:9029"
      - "--p2p.identityPrivateKey=996dceaeddcb5fc21480646f38ac53c4f5668fd33f3c0bfecfd004861d4a9dc722355dabd7f31a1266423abcf6c1db6228eb8283deb55731915ed06bd2ca387e"
      - "--p2p.peers=/ip4/172.18.211.11/tcp/15600/p2p/12D3KooWSagdVaCrS14GeJhM8CbQr41AW2PiYMgptTyAybCbQuEY,/ip4/172.18.211.12/tcp/15600/p2p/12D3KooWCKwcTWevoRKa2kEBputeGASvEBuDfRDSbe8t1DWugUmL,/ip4/172.18.211.13/tcp/15600/p2p/12D3KooWGdr8M5KX8KuKaXSiKfHJstdVnRkadYmupF7tFk2HrRoA"
      - "--p2p.peerAliases=hornet-1,hornet-2,hornet-3"
      - "--debug.enabled=true"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=172.18.211.14:9311"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.211.14:6060"
    profiles:
      - 4-nodes
  #
  # EDCAS
  #
  inx-eddn:
    container_name: inx-eddn
    image: frankthefish/inx-eddn:latest
    environment:
      - "NODE_URL=https://api.edcas.de"
      - "ZEROMQ_URL=tcp://eddn.edcd.io:9500"
      - "WALLET_PASSWORD=testwallet"
      - "WALLET_PATH=wallet/wallet.stronghold"
      - "NUM_OF_WORKERS=4"
    restart: always
    volumes:
      - ./inx-eddn/wallet:/app/wallet
  postgres:
    image: 'postgres:latest'
    env_file:
      - .postgres_env
    environment:
      - "POSTGRES_DB=edcas"
    networks:
      peering_net:
        ipv4_address: 172.18.211.40
    volumes:
      - ./postgres/:/var/lib/postgresql/data/
  inx-edcas-indexer:
    container_name: inx-edcas-indexer
    image: frankthefish/inx-edcas-indexer:latest
    env_file:
      - .postgres_env
      - .public_key_env
    environment:
      - "NODE_URL=https://api.edcas.de"
      - "NUM_OF_WORKERS=4"
      - "DATABASE_PORT=5432"
      - "DATABASE_HOST=172.18.211.40"
      - "DATABASE_NAME=edcas"
      - "TAGS=EDDN,SCAN,FSDJUMP,LOCATION,CARRIERJUMP,FSSBODYSIGNALS,SAASIGNALSFOUND"
    networks:
      peering_net:
        ipv4_address: 172.18.211.41
    restart: always
    volumes:
      - ./inx-eddn/wallet:/app/wallet
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #
  # INX
  # 
  inx-coordinator:
    container_name: inx-coordinator
    image: iotaledger/inx-coordinator:1.0-rc
    networks:
      peering_net:
        ipv4_address: 172.18.211.21
    depends_on:
      hornet-1:
        condition: service_healthy
    env_file:
      - .coordinator_env
    ports:
      - "6021:6060/tcp"
    volumes:
      - ./privatedb/state:/app/state
    command:
      - "--inx.address=172.18.211.11:9029"
      - "--coordinator.stateFilePath=state/coordinator.state"
      - "--coordinator.blockBackups.enabled=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.211.21:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes
  inx-indexer:
    container_name: inx-indexer
    image: iotaledger/inx-indexer:1.0-rc
    networks:
      peering_net:
        ipv4_address: 172.18.211.22
    depends_on:
      hornet-1:
        condition: service_healthy
    restart: on-failure
    ports:
      - "9322:9311/tcp"
      - "6022:6060/tcp"
    volumes:
      - ./privatedb/indexer:/app/database
    command:
      - "--inx.address=172.18.211.11:9029"
      - "--restAPI.bindAddress=172.18.211.22:9091"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=172.18.211.22:9311"
      - "--prometheus.goMetrics=false"
      - "--prometheus.processMetrics=false"
      - "--prometheus.restAPIMetrics=true"
      - "--prometheus.inxMetrics=true"
      - "--prometheus.promhttpMetrics=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.211.22:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes
  inx-mqtt:
    container_name: inx-mqtt
    image: iotaledger/inx-mqtt:1.0-rc
    networks:
      peering_net:
        ipv4_address: 172.18.211.23
    depends_on:
      hornet-1:
        condition: service_healthy
    restart: on-failure
    ports:
      - "9323:9311/tcp"
      - "6023:6060/tcp"
    command:
      - "--inx.address=172.18.211.11:9029"
      - "--mqtt.websocket.bindAddress=172.18.211.23:1888"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=172.18.211.23:9311"
      - "--prometheus.goMetrics=false"
      - "--prometheus.mqttMetrics=true"
      - "--prometheus.processMetrics=false"
      - "--prometheus.promhttpMetrics=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.211.23:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes
  inx-participation:
    container_name: inx-participation
    image: iotaledger/inx-participation:1.0-rc
    networks:
      peering_net:
        ipv4_address: 172.18.211.25
    depends_on:
      hornet-1:
        condition: service_healthy
    restart: on-failure
    ports:
      - "9892:9892/tcp"
      - "6025:6060/tcp"
    volumes:
      - ./privatedb/participation:/app/database
    command:
      - "--inx.address=172.18.211.11:9029"
      - "--restAPI.bindAddress=172.18.211.25:9892"
      - "--participation.db.path=/app/database"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.211.25:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes
  inx-poi:
    container_name: inx-poi
    image: iotaledger/inx-poi:1.0-rc
    networks:
      peering_net:
        ipv4_address: 172.18.211.27
    depends_on:
      hornet-1:
        condition: service_healthy
    restart: on-failure
    ports:
      - "9687:9687/tcp"
      - "6027:6060/tcp"
    command:
      - "--inx.address=172.18.211.11:9029"
      - "--restAPI.bindAddress=172.18.211.27:9687"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.211.27:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes
  inx-dashboard-1:
    container_name: inx-dashboard-1
    image: iotaledger/inx-dashboard:1.0-rc
    networks:
      peering_net:
        ipv4_address: 172.18.211.31
    depends_on:
      hornet-1:
        condition: service_healthy
    restart: on-failure
    ports:
      - "9331:9311/tcp"
      - "8011:8081/tcp"
      - "6031:6060/tcp"
    command:
      - "--inx.address=172.18.211.11:9029"
      - "--dashboard.bindAddress=172.18.211.31:8081"
      - "--dashboard.auth.passwordHash=577eb97f8faf2af47ff957b00827d6bfe9d05b810981e3073dc42553505282c1"
      - "--dashboard.auth.passwordSalt=e5d8d0bd3bb9723236177b4713a11580c55b69a51e7055dd11fa1dad3b8f6d6c"
      - "--dashboard.auth.identityPrivateKey=1f46fad4f538a031d4f87f490f6bca4319dfd0307636a5759a22b5e8874bd608f9156ba976a12918c16a481c38c88a7b5351b769adc30390e93b6c0a63b09b79"
      - "--prometheus.enabled=false"
      - "--prometheus.bindAddress=172.18.211.31:9311"
      - "--prometheus.goMetrics=false"
      - "--prometheus.processMetrics=false"
      - "--prometheus.promhttpMetrics=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.211.31:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes
  inx-dashboard-2:
    container_name: inx-dashboard-2
    image: iotaledger/inx-dashboard:1.0-rc
    networks:
      peering_net:
        ipv4_address: 172.18.211.32
    depends_on:
      hornet-2:
        condition: service_healthy
    restart: on-failure
    ports:
      - "9332:9311/tcp"
      - "8012:8081/tcp"
      - "6032:6060/tcp"
    command:
      - "--inx.address=172.18.211.12:9029"
      - "--dashboard.bindAddress=172.18.211.32:8081"
      - "--dashboard.auth.passwordHash=577eb97f8faf2af47ff957b00827d6bfe9d05b810981e3073dc42553505282c1"
      - "--dashboard.auth.passwordSalt=e5d8d0bd3bb9723236177b4713a11580c55b69a51e7055dd11fa1dad3b8f6d6c"
      - "--dashboard.auth.identityPrivateKey=a06b288ce7fc3b6f1e716f6f7d72050b53417aae4b305a68883550a3bb28597f254b082515a79391a7f13009b4133851a0c4d48e0e948809c3b46ff3e2500b4f"
      - "--prometheus.enabled=false"
      - "--prometheus.bindAddress=172.18.211.32:9311"
      - "--prometheus.goMetrics=false"
      - "--prometheus.processMetrics=false"
      - "--prometheus.promhttpMetrics=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.211.32:6060"
    profiles:
      - 2-nodes
      - 3-nodes
      - 4-nodes
  inx-dashboard-3:
    container_name: inx-dashboard-3
    image: iotaledger/inx-dashboard:1.0-rc
    networks:
      peering_net:
        ipv4_address: 172.18.211.33
    depends_on:
      hornet-3:
        condition: service_healthy
    restart: on-failure
    ports:
      - "9333:9311/tcp"
      - "8013:8081/tcp"
      - "6033:6060/tcp"
    command:
      - "--inx.address=172.18.211.13:9029"
      - "--dashboard.bindAddress=172.18.211.33:8081"
      - "--dashboard.auth.passwordHash=577eb97f8faf2af47ff957b00827d6bfe9d05b810981e3073dc42553505282c1"
      - "--dashboard.auth.passwordSalt=e5d8d0bd3bb9723236177b4713a11580c55b69a51e7055dd11fa1dad3b8f6d6c"
      - "--dashboard.auth.identityPrivateKey=5126767a84e1ced849dbbf2be809fd40f90bcfb81bd0d3309e2e25e34f803bf265500854f1f0e8fd3c389cf7b6b59cfd422b9319f257e2a8d3a772973560acdd"
      - "--prometheus.enabled=false"
      - "--prometheus.bindAddress=172.18.211.33:9311"
      - "--prometheus.goMetrics=false"
      - "--prometheus.processMetrics=false"
      - "--prometheus.promhttpMetrics=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.211.33:6060"
    profiles:
      - 3-nodes
      - 4-nodes
  inx-dashboard-4:
    container_name: inx-dashboard-4
    image: iotaledger/inx-dashboard:1.0-rc
    networks:
      peering_net:
        ipv4_address: 172.18.211.34
    depends_on:
      hornet-4:
        condition: service_healthy
    restart: on-failure
    ports:
      - "9334:9311/tcp"
      - "8014:8081/tcp"
      - "6034:6060/tcp"
    command:
      - "--inx.address=172.18.211.14:9029"
      - "--dashboard.bindAddress=172.18.211.34:8081"
      - "--dashboard.auth.passwordHash=577eb97f8faf2af47ff957b00827d6bfe9d05b810981e3073dc42553505282c1"
      - "--dashboard.auth.passwordSalt=e5d8d0bd3bb9723236177b4713a11580c55b69a51e7055dd11fa1dad3b8f6d6c"
      - "--dashboard.auth.identityPrivateKey=996dceaeddcb5fc21480646f38ac53c4f5668fd33f3c0bfecfd004861d4a9dc722355dabd7f31a1266423abcf6c1db6228eb8283deb55731915ed06bd2ca387e"
      - "--prometheus.enabled=false"
      - "--prometheus.bindAddress=172.18.211.34:9311"
      - "--prometheus.goMetrics=false"
      - "--prometheus.processMetrics=false"
      - "--prometheus.promhttpMetrics=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=172.18.211.34:6060"
    profiles:
      - 4-nodes
networks:
  peering_net:
    ipam:
      driver: default
      config:
        - subnet: "172.18.211.0/24"
